@echo off
echo Starting ServiceDeskSystem Web App and API concurrently...

echo Starting API...
start "ServiceDeskSystem API" cmd /c "dotnet run --project ServiceDeskSystem.Api/ServiceDeskSystem.Api.csproj"

echo Starting Web App...
dotnet run --project ServiceDeskSystem/ServiceDeskSystem.csproj
