// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceDeskSystem.Data;

#nullable disable

namespace ServiceDeskSystem.Migrations
{
    [DbContext(typeof(BugTrackerDbContext))]
    [Migration("20260201010854_UpdateUserRoles")]
    partial class UpdateUserRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TicketId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2024, 4, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsInternal = false,
                            Message = "Дякую за звернення. Відтворив проблему, почав аналіз.",
                            TicketId = 1
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2024, 4, 15, 15, 30, 0, 0, DateTimeKind.Utc),
                            IsInternal = true,
                            Message = "Проблема в парсингу дат - треба виправити формат для українського регіону.",
                            TicketId = 1
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 4,
                            CreatedAt = new DateTime(2024, 4, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsInternal = false,
                            Message = "This is blocking our monthly inventory audit. Please prioritize!",
                            TicketId = 3
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 5,
                            CreatedAt = new DateTime(2024, 4, 11, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsInternal = true,
                            Message = "Found the issue - race condition in sync handler. Fix ready for review.",
                            TicketId = 3
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            CreatedAt = new DateTime(2024, 4, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsInternal = false,
                            Message = "Виправлення готове, передано на тестування.",
                            TicketId = 5
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2024, 4, 19, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsInternal = false,
                            Message = "Зв'язався з технічною підтримкою LiqPay. Очікую відповідь.",
                            TicketId = 7
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2024, 4, 19, 16, 30, 0, 0, DateTimeKind.Utc),
                            IsInternal = true,
                            Message = "LiqPay змінили API endpoint. Потрібно оновити конфігурацію.",
                            TicketId = 7
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 5,
                            CreatedAt = new DateTime(2024, 3, 28, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsInternal = false,
                            Message = "Fixed by merging guest cart with user cart on login. Deployed to production.",
                            TicketId = 8
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 5,
                            CreatedAt = new DateTime(2024, 4, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsInternal = true,
                            Message = "Issue is in the USB driver timeout handling. Preparing hotfix.",
                            TicketId = 11
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2024, 4, 22, 8, 30, 0, 0, DateTimeKind.Utc),
                            IsInternal = false,
                            Message = "Проблема критична - офіс не може працювати. Потрібно відкотити прошивку!",
                            TicketId = 12
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 5,
                            CreatedAt = new DateTime(2024, 4, 22, 9, 45, 0, 0, DateTimeKind.Utc),
                            IsInternal = false,
                            Message = "Тимчасово відкотив до версії 2.0.8. Аналізую зміни в 2.1.0.",
                            TicketId = 12
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2024, 4, 16, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsInternal = false,
                            Message = "Increased buffer size and connection pool. Testing in progress.",
                            TicketId = 13
                        });
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ContactTypeId");

                    b.HasIndex("PersonId");

                    b.ToTable("ContactInfos");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.ContactType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ContactTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Email"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Phone"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Telegram"
                        });
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "System",
                            LastName = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Олександр",
                            LastName = "Коваленко",
                            MiddleName = "Петрович"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Марія",
                            LastName = "Шевченко",
                            MiddleName = "Іванівна"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "John",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Андрій",
                            LastName = "Бондаренко",
                            MiddleName = "Олегович"
                        });
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TechStackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TechStackId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentVersion = "3.2.1",
                            Description = "Програма для ведення бухгалтерського обліку підприємства",
                            Name = "Бухгалтерія Pro",
                            TechStackId = 1
                        },
                        new
                        {
                            Id = 2,
                            CurrentVersion = "2.5.0",
                            Description = "Система управління складом та інвентаризацією",
                            Name = "Warehouse Manager",
                            TechStackId = 1
                        },
                        new
                        {
                            Id = 3,
                            CurrentVersion = "1.8.3",
                            Description = "Корпоративний портал для управління персоналом",
                            Name = "HR Portal",
                            TechStackId = 2
                        },
                        new
                        {
                            Id = 4,
                            CurrentVersion = "4.1.0",
                            Description = "Платформа для онлайн-продажів з інтеграцією платіжних систем",
                            Name = "E-Commerce Platform",
                            TechStackId = 2
                        },
                        new
                        {
                            Id = 5,
                            CurrentVersion = "2.0.5",
                            Description = "Мобільний додаток для роботи з клієнтською базою",
                            Name = "Mobile CRM",
                            TechStackId = 3
                        },
                        new
                        {
                            Id = 6,
                            CurrentVersion = "1.4.2",
                            Description = "Прошивка для касових терміналів",
                            Name = "POS Terminal v2",
                            TechStackId = 4
                        },
                        new
                        {
                            Id = 7,
                            CurrentVersion = "2.1.0",
                            Description = "Контролер системи контролю доступу",
                            Name = "Smart Lock Controller",
                            TechStackId = 4
                        },
                        new
                        {
                            Id = 8,
                            CurrentVersion = "5.0.1",
                            Description = "Корпоративний маршрутизатор з підтримкою VPN",
                            Name = "Office Router Pro",
                            TechStackId = 6
                        });
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.TechStack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TechStacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C# / .NET",
                            Type = "Desktop Software"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ASP.NET Core / Blazor",
                            Type = "Web Application"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Android / Kotlin",
                            Type = "Mobile Application"
                        },
                        new
                        {
                            Id = 4,
                            Name = "C++ / Embedded",
                            Type = "Hardware Firmware"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Python / Django",
                            Type = "Web Service"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Network Infrastructure",
                            Type = "Hardware"
                        });
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StepsToReproduce")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("ProductId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffectedVersion = "3.2.1",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2024, 4, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Description = "При спробі сформувати звіт з ПДВ за останній квартал програма видає помилку 'Invalid date range'.",
                            DeveloperId = 2,
                            Environment = "Windows 11 / Chrome",
                            Priority = "High",
                            ProductId = 1,
                            Status = "In Progress",
                            StepsToReproduce = "1. Відкрити розділ Звіти\n2. Вибрати 'Звіт ПДВ'\n3. Встановити період: 01.01.2024 - 31.03.2024\n4. Натиснути 'Сформувати'",
                            Title = "Помилка при формуванні звіту ПДВ"
                        },
                        new
                        {
                            Id = 2,
                            AffectedVersion = "3.2.1",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2024, 4, 18, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Функція експорту документів в Excel формат не працює - файл створюється порожнім.",
                            Environment = "Windows 10 / Edge",
                            Priority = "Medium",
                            ProductId = 1,
                            Status = "New",
                            StepsToReproduce = "1. Відкрити будь-який документ\n2. Натиснути Експорт -> Excel\n3. Зберегти файл",
                            Title = "Не працює експорт в Excel"
                        },
                        new
                        {
                            Id = 3,
                            AffectedVersion = "2.5.0",
                            AuthorId = 4,
                            CreatedAt = new DateTime(2024, 4, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "After synchronizing with barcode scanners, the inventory count shows incorrect values for some items.",
                            DeveloperId = 5,
                            Environment = "Windows Server 2022",
                            Priority = "Critical",
                            ProductId = 2,
                            Status = "Code Review",
                            StepsToReproduce = "1. Perform physical inventory count\n2. Sync data from handheld scanners\n3. Compare totals in system",
                            Title = "Inventory count mismatch after sync"
                        },
                        new
                        {
                            Id = 4,
                            AffectedVersion = "2.5.0",
                            AuthorId = 4,
                            CreatedAt = new DateTime(2024, 4, 12, 11, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Product search takes more than 10 seconds when warehouse has more than 50,000 items.",
                            DeveloperId = 2,
                            Environment = "Windows 11",
                            Priority = "Medium",
                            ProductId = 2,
                            Status = "In Progress",
                            StepsToReproduce = "1. Open product search\n2. Enter partial product name\n3. Wait for results",
                            Title = "Slow search performance"
                        },
                        new
                        {
                            Id = 5,
                            AffectedVersion = "1.8.3",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2024, 4, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            Description = "В особистому кабінеті працівника не відображається залишок днів відпустки за поточний рік.",
                            DeveloperId = 5,
                            Environment = "Windows 10 / Firefox",
                            Priority = "High",
                            ProductId = 3,
                            Status = "Testing",
                            StepsToReproduce = "1. Увійти в особистий кабінет\n2. Перейти в розділ 'Відпустки'\n3. Перевірити баланс днів",
                            Title = "Не відображаються дні відпустки"
                        },
                        new
                        {
                            Id = 6,
                            AffectedVersion = "1.8.3",
                            AuthorId = 4,
                            CreatedAt = new DateTime(2024, 4, 20, 8, 45, 0, 0, DateTimeKind.Utc),
                            Description = "When generating PDF reports for employee attendance, the system throws an error.",
                            Environment = "macOS Ventura / Safari",
                            Priority = "Medium",
                            ProductId = 3,
                            Status = "New",
                            StepsToReproduce = "1. Go to Reports section\n2. Select Attendance Report\n3. Click Generate PDF",
                            Title = "PDF generation fails for reports"
                        },
                        new
                        {
                            Id = 7,
                            AffectedVersion = "4.1.0",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2024, 4, 19, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Клієнти не можуть завершити оплату через LiqPay - з'являється помилка 'Payment gateway timeout'.",
                            DeveloperId = 2,
                            Environment = "Android / Chrome Mobile",
                            Priority = "Critical",
                            ProductId = 4,
                            Status = "In Progress",
                            StepsToReproduce = "1. Додати товар в кошик\n2. Перейти до оформлення\n3. Вибрати оплату LiqPay\n4. Спробувати оплатити",
                            Title = "Помилка оплати через LiqPay"
                        },
                        new
                        {
                            Id = 8,
                            AffectedVersion = "4.0.5",
                            AuthorId = 4,
                            CreatedAt = new DateTime(2024, 3, 25, 14, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Items added to cart as guest user disappear after logging in to account.",
                            DeveloperId = 5,
                            Environment = "iOS / Safari",
                            Priority = "High",
                            ProductId = 4,
                            Status = "Done",
                            StepsToReproduce = "1. Browse as guest\n2. Add items to cart\n3. Click Login\n4. Enter credentials\n5. Check cart",
                            Title = "Cart items disappear after login"
                        },
                        new
                        {
                            Id = 9,
                            AffectedVersion = "2.0.5",
                            AuthorId = 4,
                            CreatedAt = new DateTime(2024, 4, 21, 9, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Users are not receiving push notifications for new tasks assigned to them.",
                            Environment = "Android 14",
                            Priority = "High",
                            ProductId = 5,
                            Status = "New",
                            StepsToReproduce = "1. Assign task to user\n2. Wait for notification\n3. Check device - no notification received",
                            Title = "Push notifications not working"
                        },
                        new
                        {
                            Id = 10,
                            AffectedVersion = "2.0.5",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2024, 4, 17, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "При синхронізації великої кількості контактів (>1000) додаток зависає і потребує перезапуску.",
                            DeveloperId = 2,
                            Environment = "iOS 17",
                            Priority = "Medium",
                            ProductId = 5,
                            Status = "In Progress",
                            StepsToReproduce = "1. Відкрити налаштування\n2. Натиснути 'Синхронізувати контакти'\n3. Дочекатися завершення",
                            Title = "Синхронізація контактів зависає"
                        },
                        new
                        {
                            Id = 11,
                            AffectedVersion = "1.4.2",
                            AuthorId = 4,
                            CreatedAt = new DateTime(2024, 4, 8, 7, 30, 0, 0, DateTimeKind.Utc),
                            Description = "The receipt printer loses connection randomly during operation, requiring terminal restart.",
                            DeveloperId = 5,
                            Environment = "POS Terminal Hardware v2",
                            Priority = "Critical",
                            ProductId = 6,
                            Status = "Code Review",
                            StepsToReproduce = "1. Process several transactions\n2. After ~20-30 receipts, printer stops responding",
                            Title = "Printer connection lost randomly"
                        },
                        new
                        {
                            Id = 12,
                            AffectedVersion = "2.1.0",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2024, 4, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Система контролю доступу не реагує на NFC картки після останнього оновлення прошивки.",
                            DeveloperId = 5,
                            Environment = "Smart Lock Hardware v3",
                            Priority = "Critical",
                            ProductId = 7,
                            Status = "In Progress",
                            StepsToReproduce = "1. Піднести NFC картку до зчитувача\n2. Очікувати відкриття замка\n3. Замок не реагує",
                            Title = "Не працює відкриття через NFC"
                        },
                        new
                        {
                            Id = 13,
                            AffectedVersion = "5.0.1",
                            AuthorId = 4,
                            CreatedAt = new DateTime(2024, 4, 14, 15, 0, 0, 0, DateTimeKind.Utc),
                            Description = "VPN connections are dropping when more than 50 concurrent users are connected.",
                            DeveloperId = 2,
                            Environment = "Office Router Pro Hardware",
                            Priority = "High",
                            ProductId = 8,
                            Status = "Testing",
                            StepsToReproduce = "1. Establish 50+ VPN connections\n2. Generate network traffic\n3. Monitor connection stability",
                            Title = "VPN tunnel drops under heavy load"
                        },
                        new
                        {
                            Id = 14,
                            AffectedVersion = "5.0.0",
                            AuthorId = 4,
                            CreatedAt = new DateTime(2024, 3, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "New firewall rules added through web interface are not being applied until device restart.",
                            DeveloperId = 5,
                            Environment = "Office Router Pro Hardware",
                            Priority = "Medium",
                            ProductId = 8,
                            Status = "Done",
                            StepsToReproduce = "1. Login to web interface\n2. Add new firewall rule\n3. Save configuration\n4. Test rule - not working",
                            Title = "Firewall rules not applying"
                        },
                        new
                        {
                            Id = 15,
                            AffectedVersion = "3.2.1",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2024, 4, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Було б зручно мати можливість переключатися на темну тему в інтерфейсі програми.",
                            Environment = "Windows 11",
                            Priority = "Low",
                            ProductId = 1,
                            Status = "New",
                            StepsToReproduce = "Це запит на нову функцію, а не баг.",
                            Title = "Запит на додавання темної теми"
                        });
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Login = "admin",
                            PasswordHash = "admin123",
                            PersonId = 1,
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Login = "o.kovalenko",
                            PasswordHash = "dev123",
                            PersonId = 2,
                            Role = "Developer"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Login = "m.shevchenko",
                            PasswordHash = "client123",
                            PersonId = 3,
                            Role = "User"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Login = "j.smith",
                            PasswordHash = "client123",
                            PersonId = 4,
                            Role = "User"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Login = "a.bondarenko",
                            PasswordHash = "dev123",
                            PersonId = 5,
                            Role = "Developer"
                        });
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Attachment", b =>
                {
                    b.HasOne("ServiceDeskSystem.Data.Entities.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Comment", b =>
                {
                    b.HasOne("ServiceDeskSystem.Data.Entities.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceDeskSystem.Data.Entities.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.ContactInfo", b =>
                {
                    b.HasOne("ServiceDeskSystem.Data.Entities.ContactType", "ContactType")
                        .WithMany("ContactInfos")
                        .HasForeignKey("ContactTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceDeskSystem.Data.Entities.Person", "Person")
                        .WithMany("ContactInfos")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactType");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Product", b =>
                {
                    b.HasOne("ServiceDeskSystem.Data.Entities.TechStack", "TechStack")
                        .WithMany("Products")
                        .HasForeignKey("TechStackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TechStack");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Ticket", b =>
                {
                    b.HasOne("ServiceDeskSystem.Data.Entities.User", "Author")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceDeskSystem.Data.Entities.User", "Developer")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ServiceDeskSystem.Data.Entities.Product", "Product")
                        .WithMany("Tickets")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Developer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.User", b =>
                {
                    b.HasOne("ServiceDeskSystem.Data.Entities.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("ServiceDeskSystem.Data.Entities.User", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.ContactType", b =>
                {
                    b.Navigation("ContactInfos");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Person", b =>
                {
                    b.Navigation("ContactInfos");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Product", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.TechStack", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Ticket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.User", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("Comments");

                    b.Navigation("CreatedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
