// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceDeskSystem.Data;

#nullable disable

namespace ServiceDeskSystem.Migrations
{
    [DbContext(typeof(BugTrackerDbContext))]
    [Migration("20260130182214_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TicketId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 12, 24, 12, 57, 18, 73, DateTimeKind.Local).AddTicks(5417),
                            IsInternal = false,
                            Message = "Maxime vel id ab sit voluptatem adipisci et voluptates dolores. Praesentium beatae nulla similique. Consequatur earum nesciunt accusantium dolor. Facere quidem nobis. Occaecati eos mollitia at possimus quasi deserunt explicabo sint quia.",
                            TicketId = 19
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 11, 23, 11, 8, 38, 551, DateTimeKind.Local).AddTicks(3223),
                            IsInternal = true,
                            Message = "Possimus fugit sit eum. Deleniti cumque sequi aut. Qui sapiente consequuntur quod inventore aut commodi.",
                            TicketId = 2
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 12, 13, 7, 38, 30, 473, DateTimeKind.Local).AddTicks(7498),
                            IsInternal = false,
                            Message = "Sed accusamus maiores non ea pariatur non aut. Provident officia dolore rerum qui.",
                            TicketId = 1
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 11, 7, 11, 12, 5, 902, DateTimeKind.Local).AddTicks(3040),
                            IsInternal = false,
                            Message = "Non magnam harum delectus quia ratione nemo iusto vel. Odio nesciunt cumque autem et. Dolor unde laboriosam nemo et sed omnis.",
                            TicketId = 10
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 12, 6, 4, 54, 37, 705, DateTimeKind.Local).AddTicks(928),
                            IsInternal = false,
                            Message = "Vel qui laborum. Numquam cupiditate accusamus labore sit facere non. Omnis adipisci aut explicabo molestiae perspiciatis voluptatem. Repellendus natus quos aut dolores eaque.",
                            TicketId = 5
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2026, 1, 9, 9, 35, 27, 339, DateTimeKind.Local).AddTicks(3277),
                            IsInternal = false,
                            Message = "Expedita quis et tempore dolorem error atque at. Minima nesciunt quibusdam consequuntur. Accusantium nisi ut suscipit fugit hic voluptatem voluptatem ad. Sunt excepturi praesentium quia pariatur ipsum aperiam mollitia architecto.",
                            TicketId = 9
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 7, 31, 5, 4, 22, 870, DateTimeKind.Local).AddTicks(6375),
                            IsInternal = false,
                            Message = "Eos veritatis velit amet molestias. Optio aut quis perferendis sit nesciunt. Enim qui culpa qui explicabo est qui enim odit.",
                            TicketId = 1
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2026, 1, 26, 7, 17, 26, 309, DateTimeKind.Local).AddTicks(2650),
                            IsInternal = false,
                            Message = "Facilis aut dolorum culpa sed et magnam necessitatibus. Architecto assumenda nihil qui sed sunt neque sint. Dolorem quis nisi. Corrupti nemo voluptatem facere a possimus facere velit nesciunt ut.",
                            TicketId = 7
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 20, 7, 39, 504, DateTimeKind.Local).AddTicks(1763),
                            IsInternal = false,
                            Message = "Tenetur et veritatis quo voluptas quia voluptas amet consectetur. Sit ratione atque sit architecto ad vel maxime qui. Molestiae ducimus aut dolores dolores.",
                            TicketId = 11
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 8, 14, 4, 57, 34, 39, DateTimeKind.Local).AddTicks(1672),
                            IsInternal = true,
                            Message = "Animi assumenda voluptas inventore. Modi quas inventore dolorem reiciendis. Error sit id est molestiae eos consectetur natus mollitia qui.",
                            TicketId = 7
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 12, 25, 8, 43, 34, 70, DateTimeKind.Local).AddTicks(7636),
                            IsInternal = false,
                            Message = "Nihil excepturi ea eum animi assumenda error. Autem porro a impedit ab officiis. Incidunt suscipit laudantium aut molestiae possimus non ea. Enim voluptatem qui fuga molestias eligendi odio unde soluta.",
                            TicketId = 11
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 12, 14, 15, 30, 37, 82, DateTimeKind.Local).AddTicks(9869),
                            IsInternal = false,
                            Message = "Autem et voluptatem incidunt quia. Atque molestias est saepe.",
                            TicketId = 18
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 11, 24, 8, 5, 13, 562, DateTimeKind.Local).AddTicks(338),
                            IsInternal = true,
                            Message = "Dolor aut fuga occaecati culpa hic itaque voluptates nobis. Velit doloremque qui quasi ratione. Sit aspernatur dicta enim iusto exercitationem. Mollitia dolorem sint explicabo. Facilis hic culpa molestiae sint pariatur fuga et.",
                            TicketId = 16
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 11, 8, 7, 59, 7, 432, DateTimeKind.Local).AddTicks(7873),
                            IsInternal = true,
                            Message = "Unde non assumenda blanditiis fugit expedita. Qui natus voluptas sed qui autem aut sint. Eligendi veritatis at. Ut id cumque atque.",
                            TicketId = 9
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 8, 26, 12, 47, 26, 844, DateTimeKind.Local).AddTicks(3413),
                            IsInternal = false,
                            Message = "Enim et harum voluptatem maxime voluptatem eum. In odio maiores dolore iure. Iure laudantium rem quod sint aut itaque quisquam doloribus.",
                            TicketId = 17
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 8, 17, 14, 49, 44, 684, DateTimeKind.Local).AddTicks(5347),
                            IsInternal = false,
                            Message = "Similique non doloremque et aut. Exercitationem qui aliquid dolores et velit. Nam velit eius sit ut.",
                            TicketId = 13
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 11, 19, 9, 44, 18, 5, DateTimeKind.Local).AddTicks(9864),
                            IsInternal = true,
                            Message = "Eius laborum deserunt magnam. Debitis recusandae aperiam perspiciatis. Eum incidunt a. Autem commodi explicabo facilis.",
                            TicketId = 18
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 9, 25, 12, 55, 57, 923, DateTimeKind.Local).AddTicks(2270),
                            IsInternal = false,
                            Message = "Culpa aliquam consequuntur. Ut consectetur cumque dolores molestias eum. In eos quae nam rem sed et expedita corporis. Sit quaerat fugiat ut occaecati alias repellat tenetur aspernatur.",
                            TicketId = 20
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 12, 10, 10, 53, 41, 592, DateTimeKind.Local).AddTicks(7197),
                            IsInternal = false,
                            Message = "Facere totam est ex quia suscipit est magni laboriosam reiciendis. Quae voluptatibus est ea et aliquam enim. Qui asperiores exercitationem dolores. Amet cumque perspiciatis velit corrupti sed ea quia autem.",
                            TicketId = 15
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 12, 23, 8, 31, 58, 550, DateTimeKind.Local).AddTicks(5717),
                            IsInternal = false,
                            Message = "Et praesentium magni quos asperiores sit a sit corporis eligendi. Ab nobis ipsam. Et praesentium aut eos dolorem.",
                            TicketId = 7
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 10, 3, 13, 27, 45, 337, DateTimeKind.Local).AddTicks(2552),
                            IsInternal = true,
                            Message = "Dolor tempore modi non libero enim tenetur. Quisquam itaque et et et. Tempora nobis labore porro reprehenderit atque quisquam aut aspernatur. Voluptatem omnis quasi dolores ex impedit qui corrupti est. Voluptas veniam quibusdam autem accusantium repellendus.",
                            TicketId = 12
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 10, 8, 7, 0, 14, 785, DateTimeKind.Local).AddTicks(9541),
                            IsInternal = false,
                            Message = "Rem illo earum itaque omnis mollitia dolore voluptatem. Dolorem in consequatur nam et et qui aut aut.",
                            TicketId = 3
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 11, 25, 15, 59, 59, 111, DateTimeKind.Local).AddTicks(4735),
                            IsInternal = false,
                            Message = "Necessitatibus et est est iure consequatur esse omnis vel id. Perferendis adipisci quam nesciunt perspiciatis. Consequatur similique tempore impedit. Impedit quia ut ad autem qui. Nam unde reprehenderit sunt asperiores ab nobis.",
                            TicketId = 19
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2026, 1, 8, 16, 45, 28, 728, DateTimeKind.Local).AddTicks(3865),
                            IsInternal = false,
                            Message = "Iste veritatis et incidunt et iste pariatur magnam eos. Excepturi exercitationem ut praesentium sequi similique et aut. Eum eius voluptatem illo eveniet molestiae velit consequatur rem quidem. Iusto vitae sint eveniet accusamus facilis molestias. Est qui id nostrum cupiditate.",
                            TicketId = 16
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 8, 31, 10, 9, 46, 335, DateTimeKind.Local).AddTicks(4177),
                            IsInternal = false,
                            Message = "Laboriosam sunt qui dolores molestiae deserunt voluptate. Porro corporis molestiae. Autem laborum ut corporis. Autem laboriosam officia molestias veritatis possimus.",
                            TicketId = 2
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 9, 28, 5, 31, 12, 84, DateTimeKind.Local).AddTicks(143),
                            IsInternal = false,
                            Message = "Sit consequuntur odio omnis. Exercitationem accusantium laborum officia asperiores corporis laudantium quidem temporibus consequatur. Harum ea cum maiores. Ducimus nihil quam alias voluptatem minima illum.",
                            TicketId = 17
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 10, 5, 8, 13, 26, 201, DateTimeKind.Local).AddTicks(7038),
                            IsInternal = false,
                            Message = "Optio dolor doloribus velit et ipsam excepturi eligendi nulla. Eaque quia accusamus enim placeat labore. Qui magnam quidem quod similique nihil sit. Et sit non magnam voluptatem nesciunt quidem soluta officiis. Eum ut eius.",
                            TicketId = 10
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 44, 0, 963, DateTimeKind.Local).AddTicks(6595),
                            IsInternal = false,
                            Message = "Eum debitis voluptatem. Et consequuntur dolor. Esse ratione voluptatem. Rem ut quidem molestias.",
                            TicketId = 9
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 8, 22, 21, 45, 12, 238, DateTimeKind.Local).AddTicks(986),
                            IsInternal = true,
                            Message = "Dignissimos asperiores dolor et consequatur quia. Necessitatibus neque non delectus nam quidem ut est aut.",
                            TicketId = 10
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 8, 28, 3, 20, 53, 256, DateTimeKind.Local).AddTicks(849),
                            IsInternal = false,
                            Message = "At sapiente ex voluptatem qui quam veritatis. Quis accusantium qui maiores.",
                            TicketId = 17
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 8, 30, 1, 16, 5, 858, DateTimeKind.Local).AddTicks(4364),
                            IsInternal = true,
                            Message = "Ullam non voluptatibus explicabo neque consequatur. Id id nostrum nesciunt ipsam.",
                            TicketId = 4
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 8, 4, 4, 31, 12, 830, DateTimeKind.Local).AddTicks(7154),
                            IsInternal = true,
                            Message = "Error quod quod eum. Doloribus iste earum nulla est laudantium dolorum dolor repellat.",
                            TicketId = 16
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 10, 8, 18, 44, 5, 618, DateTimeKind.Local).AddTicks(1232),
                            IsInternal = false,
                            Message = "Quibusdam unde non nulla soluta assumenda sit inventore non. Consequatur non perferendis laborum culpa vel quisquam sint. Asperiores sed modi sapiente nobis enim sed fugit. Enim architecto voluptate atque.",
                            TicketId = 9
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 12, 4, 6, 3, 4, 125, DateTimeKind.Local).AddTicks(9754),
                            IsInternal = false,
                            Message = "Cumque inventore ut dolores aut consectetur voluptas itaque est error. Fuga corporis quo asperiores iste modi. Officia dolore in error expedita vero placeat. Dolore voluptas dolor harum adipisci similique sunt dolorem numquam. Voluptatem eaque non est voluptas suscipit excepturi unde.",
                            TicketId = 16
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 9, 2, 22, 28, 1, 572, DateTimeKind.Local).AddTicks(3098),
                            IsInternal = false,
                            Message = "Sequi voluptas molestiae natus ipsam dolores ea fugit placeat. Earum excepturi omnis aut. Pariatur ab voluptatum fuga aliquid.",
                            TicketId = 8
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 9, 21, 22, 32, 16, 70, DateTimeKind.Local).AddTicks(8349),
                            IsInternal = false,
                            Message = "Illo odit sed inventore. Soluta quo eum. Aliquid eos aut excepturi vitae labore.",
                            TicketId = 2
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 9, 16, 22, 36, 31, 869, DateTimeKind.Local).AddTicks(6960),
                            IsInternal = true,
                            Message = "Sed dolor necessitatibus quidem nostrum rerum eos. Ut deleniti laborum sequi architecto. Exercitationem asperiores est.",
                            TicketId = 14
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2026, 1, 7, 15, 13, 50, 491, DateTimeKind.Local).AddTicks(6929),
                            IsInternal = false,
                            Message = "Impedit ipsa delectus. Aut fuga eveniet nemo voluptatibus beatae libero. Non tempora nihil autem minus optio quia.",
                            TicketId = 11
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 9, 19, 13, 51, 17, 2, DateTimeKind.Local).AddTicks(3324),
                            IsInternal = true,
                            Message = "Earum sint mollitia. Sunt et velit eaque neque sit deserunt voluptas ea doloremque. Architecto ipsum harum beatae ea natus consequatur voluptas.",
                            TicketId = 11
                        },
                        new
                        {
                            Id = 40,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 8, 5, 23, 51, 53, 630, DateTimeKind.Local).AddTicks(5094),
                            IsInternal = false,
                            Message = "Qui sit sit non ut dolorem impedit ullam voluptatem velit. Totam atque assumenda quae eum totam. Libero corrupti et cumque saepe.",
                            TicketId = 9
                        },
                        new
                        {
                            Id = 41,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2026, 1, 5, 20, 46, 54, 667, DateTimeKind.Local).AddTicks(7769),
                            IsInternal = false,
                            Message = "Impedit ipsa cum rerum ipsa. Repellat voluptate et.",
                            TicketId = 19
                        },
                        new
                        {
                            Id = 42,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 8, 23, 14, 50, 52, 801, DateTimeKind.Local).AddTicks(3078),
                            IsInternal = false,
                            Message = "Et itaque beatae animi. Iusto consequatur velit enim voluptas natus odio quis. Quos aspernatur deserunt natus delectus est. Placeat occaecati odio placeat quae. Nam laudantium aut natus expedita pariatur.",
                            TicketId = 2
                        },
                        new
                        {
                            Id = 43,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 11, 3, 21, 9, 55, 700, DateTimeKind.Local).AddTicks(1394),
                            IsInternal = false,
                            Message = "Eveniet ut nulla commodi sit atque. Quo consequatur nemo voluptas ad consequatur consequatur. At ut esse quidem. Tempore perferendis qui minus molestias sed ut deserunt laborum. Qui id et magni quasi.",
                            TicketId = 8
                        },
                        new
                        {
                            Id = 44,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 12, 3, 9, 53, 14, 961, DateTimeKind.Local).AddTicks(4297),
                            IsInternal = true,
                            Message = "Suscipit esse ex cumque. Consectetur pariatur est qui incidunt soluta est. Facere rerum possimus. Vero voluptatibus culpa. Aut qui repudiandae doloremque expedita labore quod provident sit excepturi.",
                            TicketId = 14
                        },
                        new
                        {
                            Id = 45,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2026, 1, 25, 4, 44, 13, 531, DateTimeKind.Local).AddTicks(2425),
                            IsInternal = true,
                            Message = "Aperiam reiciendis aut illo voluptatibus temporibus quae quo aut. Autem amet hic voluptate non ex. Amet ut nobis dignissimos tempore. Tenetur aut architecto quos porro id ipsa dignissimos esse.",
                            TicketId = 2
                        },
                        new
                        {
                            Id = 46,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 9, 14, 6, 34, 38, 238, DateTimeKind.Local).AddTicks(3137),
                            IsInternal = true,
                            Message = "Alias enim nobis velit sit neque eos. Culpa et maiores quisquam enim quos odit. Nisi commodi odit illo earum voluptates ullam sit aut delectus. Sapiente eveniet voluptatibus. Est eum voluptas amet et.",
                            TicketId = 14
                        },
                        new
                        {
                            Id = 47,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 10, 3, 19, 54, 10, 40, DateTimeKind.Local).AddTicks(8639),
                            IsInternal = true,
                            Message = "Quos similique minus aut minus tenetur nemo. Fuga porro omnis sint officia explicabo.",
                            TicketId = 2
                        },
                        new
                        {
                            Id = 48,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 11, 27, 21, 36, 12, 423, DateTimeKind.Local).AddTicks(5581),
                            IsInternal = true,
                            Message = "Expedita animi deserunt suscipit laboriosam totam nemo sit et aspernatur. Qui delectus eum esse qui animi incidunt ut.",
                            TicketId = 11
                        },
                        new
                        {
                            Id = 49,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 9, 16, 6, 1, 30, 785, DateTimeKind.Local).AddTicks(9105),
                            IsInternal = true,
                            Message = "Totam aliquam sunt voluptates est neque id deserunt amet. Saepe reiciendis qui perspiciatis ut est quia totam non aut. Hic sed cum minima facere vero. Voluptatem magnam dolores et voluptatibus laudantium officiis non numquam.",
                            TicketId = 19
                        },
                        new
                        {
                            Id = 50,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2025, 10, 8, 7, 4, 22, 827, DateTimeKind.Local).AddTicks(6668),
                            IsInternal = false,
                            Message = "Atque cupiditate facere quia est delectus ducimus non illo. Id quos sint ab esse et eveniet corporis repellendus. Itaque assumenda est repellat non libero inventore. Pariatur non deserunt et in ipsum. Sequi non unde dolorem pariatur sunt quisquam beatae.",
                            TicketId = 20
                        });
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ContactTypeId");

                    b.HasIndex("PersonId");

                    b.ToTable("ContactInfos");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.ContactType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ContactTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Email"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Phone"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Telegram"
                        });
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Admin",
                            LastName = "Administrator",
                            MiddleName = "System"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Іван",
                            LastName = "Петренко",
                            MiddleName = "Олександрович"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Марія",
                            LastName = "Коваленко",
                            MiddleName = "Іванівна"
                        });
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TechStackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TechStackId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentVersion = "4.0.8.5",
                            Description = "Vel id ab sit voluptatem adipisci et voluptates dolores consectetur.",
                            Name = "Tasty Fresh Fish",
                            TechStackId = 2
                        },
                        new
                        {
                            Id = 2,
                            CurrentVersion = "8.7.0.5",
                            Description = "Accusantium dolor alias facere quidem nobis eveniet occaecati eos mollitia.",
                            Name = "Small Frozen Keyboard",
                            TechStackId = 1
                        },
                        new
                        {
                            Id = 3,
                            CurrentVersion = "4.7.1.0",
                            Description = "Quibusdam recusandae necessitatibus quos consectetur possimus fugit sit eum neque.",
                            Name = "Unbranded Concrete Shirt",
                            TechStackId = 3
                        },
                        new
                        {
                            Id = 4,
                            CurrentVersion = "1.8.9.9",
                            Description = "Quod inventore aut commodi sed et illo aperiam inventore id.",
                            Name = "Licensed Frozen Keyboard",
                            TechStackId = 2
                        },
                        new
                        {
                            Id = 5,
                            CurrentVersion = "4.8.2.2",
                            Description = "Enim provident officia dolore rerum qui ullam id ipsa odio.",
                            Name = "Refined Concrete Chair",
                            TechStackId = 4
                        });
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.TechStack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TechStacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C# / .NET",
                            Type = "Backend"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Blazor",
                            Type = "Web"
                        },
                        new
                        {
                            Id = 3,
                            Name = "React",
                            Type = "Web"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SQL Server",
                            Type = "Database"
                        },
                        new
                        {
                            Id = 5,
                            Name = "C++ STM32",
                            Type = "Embedded"
                        });
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StepsToReproduce")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("ProductId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffectedVersion = "1.0.5.8",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 12, 14, 6, 17, 31, 86, DateTimeKind.Local).AddTicks(2347),
                            Description = "Voluptatem adipisci et. Dolores consectetur praesentium beatae nulla similique aliquam consequatur earum nesciunt. Dolor alias facere.",
                            DeveloperId = 2,
                            Environment = "macOS Ventura / Chrome",
                            Priority = "High",
                            ProductId = 1,
                            Status = "Testing",
                            StepsToReproduce = "Nobis eveniet occaecati eos mollitia at possimus quasi.\nExplicabo sint quia voluptate quibusdam recusandae necessitatibus.\nConsectetur possimus fugit sit eum neque.",
                            Title = "Maiores voluptates maxime vel id"
                        },
                        new
                        {
                            Id = 2,
                            AffectedVersion = "3.8.5.5",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 10, 30, 4, 10, 21, 135, DateTimeKind.Local).AddTicks(7933),
                            Description = "Sed accusamus maiores non ea pariatur non aut. Provident officia dolore rerum qui. Id ipsa odio odio voluptas.",
                            DeveloperId = 2,
                            Environment = "Windows 11 / Edge",
                            Priority = "Medium",
                            ProductId = 3,
                            Status = "In Progress",
                            StepsToReproduce = "Magnam harum delectus quia.\nNemo iusto vel quaerat.\nNesciunt cumque autem et sint dolor.",
                            Title = "Commodi sed et illo aperiam"
                        },
                        new
                        {
                            Id = 3,
                            AffectedVersion = "5.3.1.9",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 9, 19, 15, 34, 16, 399, DateTimeKind.Local).AddTicks(376),
                            Description = "Accusamus labore sit facere non ut omnis. Aut explicabo molestiae perspiciatis. Iure repellendus natus quos aut.",
                            DeveloperId = 2,
                            Environment = "Windows 10 / Firefox",
                            Priority = "Critical",
                            ProductId = 5,
                            Status = "In Progress",
                            StepsToReproduce = "Eaque cum optio sed.\nSoluta minus expedita quis et tempore.\nError atque at velit minima nesciunt quibusdam consequuntur voluptas.",
                            Title = "Veritatis vel qui laborum deserunt"
                        },
                        new
                        {
                            Id = 4,
                            AffectedVersion = "7.4.3.5",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 11, 3, 2, 22, 22, 697, DateTimeKind.Local).AddTicks(1046),
                            Description = "Architecto deleniti aut ea omnis suscipit ut. Veritatis velit amet molestias in optio aut quis perferendis. Nesciunt et enim qui culpa.",
                            DeveloperId = 2,
                            Environment = "Windows 10 / Chrome",
                            Priority = "Medium",
                            ProductId = 1,
                            Status = "New",
                            StepsToReproduce = "Explicabo est qui enim odit nemo.\nDoloremque et natus.\nFacilis aut dolorum culpa sed et magnam necessitatibus.",
                            Title = "Excepturi praesentium quia pariatur ipsum"
                        },
                        new
                        {
                            Id = 5,
                            AffectedVersion = "7.0.3.2",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 8, 30, 4, 38, 29, 73, DateTimeKind.Local).AddTicks(3908),
                            Description = "A possimus facere velit nesciunt ut quo aut voluptas. Reprehenderit facere tenetur et veritatis quo. Quia voluptas amet consectetur est sit ratione atque sit.",
                            Environment = "Ubuntu 22.04 / Chrome",
                            Priority = "Medium",
                            ProductId = 5,
                            Status = "Testing",
                            StepsToReproduce = "Ad vel maxime.\nIpsam molestiae ducimus aut dolores dolores.\nSint et qui quam quia.",
                            Title = "Quis nisi eveniet corrupti nemo"
                        },
                        new
                        {
                            Id = 6,
                            AffectedVersion = "5.7.1.3",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 9, 27, 21, 55, 15, 936, DateTimeKind.Local).AddTicks(234),
                            Description = "Natus mollitia qui explicabo. Quia molestias est. Nihil excepturi ea eum animi assumenda error.",
                            DeveloperId = 2,
                            Environment = "macOS Ventura / Edge",
                            Priority = "Medium",
                            ProductId = 2,
                            Status = "Done",
                            StepsToReproduce = "Autem porro a impedit ab officiis.\nIncidunt suscipit laudantium aut molestiae possimus non ea.\nEnim voluptatem qui fuga molestias eligendi odio unde soluta.",
                            Title = "Error sit id est molestiae"
                        },
                        new
                        {
                            Id = 7,
                            AffectedVersion = "4.7.3.5",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 11, 23, 22, 52, 32, 506, DateTimeKind.Local).AddTicks(6427),
                            Description = "Eos fuga omnis consequatur dolor aut fuga occaecati. Hic itaque voluptates nobis minima velit doloremque. Quasi ratione totam sit aspernatur dicta. Iusto exercitationem adipisci mollitia dolorem. Explicabo minus facilis hic culpa molestiae sint. Fuga et eos harum repellendus nulla soluta velit unde.",
                            Environment = "Windows 11 / Chrome",
                            Priority = "Critical",
                            ProductId = 1,
                            Status = "Code Review",
                            StepsToReproduce = "Assumenda blanditiis fugit expedita maxime qui natus voluptas sed qui.\nAut sint accusantium eligendi veritatis at.\nUt id cumque atque.",
                            Title = "Dolor atque molestias est saepe"
                        },
                        new
                        {
                            Id = 8,
                            AffectedVersion = "6.0.5.2",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 10, 2, 15, 21, 14, 652, DateTimeKind.Local).AddTicks(4777),
                            Description = "Iure vel iure laudantium. Quod sint aut itaque quisquam doloribus. Ratione vel incidunt quis ut similique. Doloremque et aut qui. Qui aliquid dolores et velit. Nam velit eius sit ut.",
                            Environment = "Windows 10 / Firefox",
                            Priority = "Low",
                            ProductId = 1,
                            Status = "Done",
                            StepsToReproduce = "Aspernatur facilis architecto nihil sed eius laborum deserunt magnam nesciunt.\nRecusandae aperiam perspiciatis voluptatem eum incidunt a sit autem commodi.\nFacilis quia id.",
                            Title = "Voluptatem eum consequatur in odio"
                        },
                        new
                        {
                            Id = 9,
                            AffectedVersion = "5.4.1.4",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2026, 1, 22, 21, 11, 39, 256, DateTimeKind.Local).AddTicks(8770),
                            Description = "Nam rem sed. Expedita corporis quo sit quaerat fugiat ut. Alias repellat tenetur aspernatur laboriosam nemo repellat. Tempore ut facere totam est ex quia. Est magni laboriosam reiciendis quas. Voluptatibus est ea.",
                            DeveloperId = 2,
                            Environment = "macOS Ventura / Chrome",
                            Priority = "High",
                            ProductId = 1,
                            Status = "Done",
                            StepsToReproduce = "Aliquam enim eius qui.\nExercitationem dolores dolorem amet cumque perspiciatis velit corrupti sed ea.\nAutem omnis quisquam id non.",
                            Title = "Dolores molestias eum nulla in"
                        },
                        new
                        {
                            Id = 10,
                            AffectedVersion = "3.0.6.4",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2026, 1, 19, 14, 15, 26, 748, DateTimeKind.Local).AddTicks(9650),
                            Description = "Praesentium aut eos dolorem dolorum temporibus ipsam rerum aut sunt. Tempore modi non libero. Tenetur sit quisquam itaque et. Et aut tempora nobis labore porro reprehenderit atque quisquam.",
                            DeveloperId = 2,
                            Environment = "Windows 10 / Safari",
                            Priority = "High",
                            ProductId = 3,
                            Status = "Code Review",
                            StepsToReproduce = "Aspernatur at voluptatem.\nQuasi dolores ex impedit qui corrupti est quam voluptas.\nQuibusdam autem accusantium repellendus aspernatur.",
                            Title = "Eligendi explicabo ab nobis ipsam"
                        },
                        new
                        {
                            Id = 11,
                            AffectedVersion = "6.9.4.7",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 8, 11, 9, 23, 46, 856, DateTimeKind.Local).AddTicks(8909),
                            Description = "Et et qui aut aut autem autem aut. Delectus rerum necessitatibus. Est est iure consequatur esse omnis vel id nostrum. Adipisci quam nesciunt.",
                            DeveloperId = 2,
                            Environment = "macOS Ventura / Edge",
                            Priority = "Medium",
                            ProductId = 4,
                            Status = "Done",
                            StepsToReproduce = "Labore consequatur similique tempore impedit molestiae impedit.\nUt ad autem.\nUt nam unde reprehenderit sunt asperiores ab.",
                            Title = "Dolore voluptatem at dolorem in"
                        },
                        new
                        {
                            Id = 12,
                            AffectedVersion = "6.2.0.1",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2026, 1, 20, 11, 19, 26, 133, DateTimeKind.Local).AddTicks(2986),
                            Description = "Exercitationem ut praesentium sequi similique et aut. Eum eius voluptatem illo eveniet molestiae velit consequatur rem quidem. Iusto vitae sint eveniet accusamus facilis molestias. Est qui id nostrum cupiditate. Aut quibusdam omnis officia provident laboriosam sunt qui dolores.",
                            DeveloperId = 2,
                            Environment = "Windows 11 / Safari",
                            Priority = "Critical",
                            ProductId = 2,
                            Status = "Done",
                            StepsToReproduce = "Deserunt voluptate aut porro corporis molestiae consectetur autem laborum ut.\nEt autem laboriosam officia molestias.\nPossimus praesentium ipsum.",
                            Title = "Et iste pariatur magnam eos"
                        },
                        new
                        {
                            Id = 13,
                            AffectedVersion = "0.3.8.1",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 8, 22, 20, 58, 22, 475, DateTimeKind.Local).AddTicks(789),
                            Description = "Consequatur modi harum ea cum maiores quas ducimus nihil. Alias voluptatem minima illum commodi quia. Nam dolor omnis optio dolor doloribus velit et ipsam. Eligendi nulla vel eaque quia accusamus enim. Labore ut qui magnam quidem quod similique nihil.",
                            DeveloperId = 2,
                            Environment = "Windows 10 / Chrome",
                            Priority = "Low",
                            ProductId = 4,
                            Status = "Testing",
                            StepsToReproduce = "Omnis et sit.\nMagnam voluptatem nesciunt quidem.\nOfficiis sunt eum ut eius non ea voluptatum.",
                            Title = "Laborum officia asperiores corporis laudantium"
                        },
                        new
                        {
                            Id = 14,
                            AffectedVersion = "4.6.1.9",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 12, 17, 1, 39, 17, 833, DateTimeKind.Local).AddTicks(7787),
                            Description = "Molestias ullam corporis odio culpa modi in dignissimos. Dolor et consequatur quia et necessitatibus neque non delectus nam. Ut est aut qui consequuntur atque inventore modi. At sapiente ex voluptatem qui quam veritatis. Quis accusantium qui maiores. Sequi eum ratione quia praesentium ullam.",
                            DeveloperId = 2,
                            Environment = "Windows 10 / Chrome",
                            Priority = "Low",
                            ProductId = 4,
                            Status = "Testing",
                            StepsToReproduce = "Voluptatibus explicabo neque consequatur sit id id.\nNesciunt ipsam aspernatur neque quia.\nQui numquam error quod quod eum dolorem doloribus iste earum.",
                            Title = "Esse ratione voluptatem magni rem"
                        },
                        new
                        {
                            Id = 15,
                            AffectedVersion = "6.7.5.4",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 20, 18, 12, 131, DateTimeKind.Local).AddTicks(9763),
                            Description = "Sit inventore non expedita consequatur non perferendis laborum culpa. Quisquam sint cumque asperiores sed modi. Nobis enim sed fugit nesciunt enim architecto voluptate atque aliquid. Esse perferendis consequatur saepe cumque inventore. Dolores aut consectetur voluptas itaque est error esse fuga corporis.",
                            DeveloperId = 2,
                            Environment = "macOS Ventura / Chrome",
                            Priority = "Medium",
                            ProductId = 3,
                            Status = "Testing",
                            StepsToReproduce = "Asperiores iste modi in officia dolore in error expedita.\nPlaceat vero dolore voluptas dolor harum adipisci similique sunt.\nNumquam facilis voluptatem eaque non est voluptas suscipit excepturi.",
                            Title = "Omnis quibusdam unde non nulla"
                        },
                        new
                        {
                            Id = 16,
                            AffectedVersion = "2.9.4.6",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 8, 14, 15, 28, 41, 440, DateTimeKind.Local).AddTicks(2853),
                            Description = "Excepturi omnis aut quis pariatur ab voluptatum fuga aliquid sed. Commodi vel voluptate et. Odit sed inventore.",
                            Environment = "Windows 10 / Chrome",
                            Priority = "Low",
                            ProductId = 2,
                            Status = "New",
                            StepsToReproduce = "Soluta quo eum.\nAliquid eos aut excepturi vitae labore.\nQuis illo fugiat voluptas in sed dolor necessitatibus quidem nostrum.",
                            Title = "Ipsam dolores ea fugit placeat"
                        },
                        new
                        {
                            Id = 17,
                            AffectedVersion = "2.5.9.2",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 9, 2, 8, 47, 49, 881, DateTimeKind.Local).AddTicks(6319),
                            Description = "Impedit ipsa delectus. Aut fuga eveniet nemo voluptatibus beatae libero. Non tempora nihil autem minus optio quia. Officiis non vero odio alias earum sint.",
                            DeveloperId = 2,
                            Environment = "macOS Ventura / Chrome",
                            Priority = "Low",
                            ProductId = 1,
                            Status = "In Progress",
                            StepsToReproduce = "Maiores sunt et velit eaque neque sit.\nVoluptas ea doloremque quidem architecto ipsum harum.\nEa natus consequatur.",
                            Title = "Est quasi voluptatem cum autem"
                        },
                        new
                        {
                            Id = 18,
                            AffectedVersion = "3.7.5.4",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 10, 16, 8, 33, 4, 915, DateTimeKind.Local).AddTicks(6999),
                            Description = "Totam atque assumenda quae eum totam. Libero corrupti et cumque saepe. Aperiam odio in voluptatem sit impedit ipsa cum rerum. Sit repellat voluptate.",
                            DeveloperId = 2,
                            Environment = "Ubuntu 22.04 / Chrome",
                            Priority = "Low",
                            ProductId = 4,
                            Status = "Testing",
                            StepsToReproduce = "Et et molestiae est at eius et itaque beatae.\nQuisquam iusto consequatur velit enim voluptas natus.\nQuis ea quos aspernatur deserunt natus.",
                            Title = "Ut dolorem impedit ullam voluptatem"
                        },
                        new
                        {
                            Id = 19,
                            AffectedVersion = "4.3.6.5",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 59, 54, 938, DateTimeKind.Local).AddTicks(7038),
                            Description = "Commodi aut molestiae. Ut nulla commodi sit atque in quo consequatur nemo voluptas. Consequatur consequatur et at ut.",
                            DeveloperId = 2,
                            Environment = "Windows 10 / Safari",
                            Priority = "Critical",
                            ProductId = 5,
                            Status = "In Progress",
                            StepsToReproduce = "Quidem at tempore perferendis qui minus.\nSed ut deserunt laborum ad qui id.\nMagni quasi impedit occaecati iure laboriosam tenetur.",
                            Title = "Aut natus expedita pariatur cum"
                        },
                        new
                        {
                            Id = 20,
                            AffectedVersion = "6.1.0.1",
                            AuthorId = 3,
                            CreatedAt = new DateTime(2025, 11, 14, 22, 59, 36, 803, DateTimeKind.Local).AddTicks(9026),
                            Description = "Vero voluptatibus culpa. Aut qui repudiandae doloremque expedita labore quod provident sit excepturi. Soluta soluta laboriosam. Temporibus aperiam reiciendis aut illo voluptatibus temporibus. Quo aut quos. Amet hic voluptate non ex quis.",
                            Environment = "macOS Ventura / Edge",
                            Priority = "Critical",
                            ProductId = 5,
                            Status = "In Progress",
                            StepsToReproduce = "Ut nobis dignissimos tempore.\nTenetur aut architecto quos porro id ipsa dignissimos esse.\nUt beatae aut aut non.",
                            Title = "Soluta est quia facere rerum"
                        });
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "admin",
                            PasswordHash = "$2a$11$dummyHashForTestingPurposesOnly123456",
                            PersonId = 1,
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Login = "developer",
                            PasswordHash = "$2a$11$dummyHashForTestingPurposesOnly123456",
                            PersonId = 2,
                            Role = "Developer"
                        },
                        new
                        {
                            Id = 3,
                            Login = "client",
                            PasswordHash = "$2a$11$dummyHashForTestingPurposesOnly123456",
                            PersonId = 3,
                            Role = "Client"
                        });
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Attachment", b =>
                {
                    b.HasOne("ServiceDeskSystem.Data.Entities.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Comment", b =>
                {
                    b.HasOne("ServiceDeskSystem.Data.Entities.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceDeskSystem.Data.Entities.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.ContactInfo", b =>
                {
                    b.HasOne("ServiceDeskSystem.Data.Entities.ContactType", "ContactType")
                        .WithMany("ContactInfos")
                        .HasForeignKey("ContactTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceDeskSystem.Data.Entities.Person", "Person")
                        .WithMany("ContactInfos")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactType");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Product", b =>
                {
                    b.HasOne("ServiceDeskSystem.Data.Entities.TechStack", "TechStack")
                        .WithMany("Products")
                        .HasForeignKey("TechStackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TechStack");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Ticket", b =>
                {
                    b.HasOne("ServiceDeskSystem.Data.Entities.User", "Author")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceDeskSystem.Data.Entities.User", "Developer")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ServiceDeskSystem.Data.Entities.Product", "Product")
                        .WithMany("Tickets")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Developer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.User", b =>
                {
                    b.HasOne("ServiceDeskSystem.Data.Entities.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("ServiceDeskSystem.Data.Entities.User", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.ContactType", b =>
                {
                    b.Navigation("ContactInfos");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Person", b =>
                {
                    b.Navigation("ContactInfos");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Product", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.TechStack", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.Ticket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ServiceDeskSystem.Data.Entities.User", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("Comments");

                    b.Navigation("CreatedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
