# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ServiceDeskSystem.sln
      
    - name: Build
      run: dotnet build ServiceDeskSystem.sln --configuration Release --no-restore
      
    - name: Test
      run: dotnet test ServiceDeskSystem.sln --configuration Release --no-build --verbosity normal
